#!/usr/bin/ruby

# CURSETALK
# Pulls a random curse word out of a curses dictionary every second and
# says it


while true do
  print c = `./curse`.chomp + " "
  $stdout.flush
  `say -v Alex "#{c}"`
  sleep 1
end
